---
- name: "Download Filebeat's deb"
  when: filebeat_install_type == 'remote'
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "files/filebeat-{{ filebeat_version }}-amd64.deb"
    validate_certs: false
  register: download_filebeat
  delegate_to: localhost
  until: download_filebeat is succeeded
  tags: [download]

- name: Copy Filebeat to managed node
  copy:
    src: "files/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    mode: 0755
