---
  - name: Set filebeat systemwork
    changed_when: filebeat_modules.stdout != 'Module system is alredy enabled'
    become: true
    command:
      cmd: filebeat modules enable system
      chdir: /usr/share/filebeat/bin
    register: filebeat_modules

  
  - name: Load Kibana dashboard
    changed_when: false
    become: true
    command:  
      cmd: filebeat setup
      chdir: /usr/share/filebeat/bin
    register: filebeat_setup
    until: filebeat_setup is succeeded